import PokemonUrl from "./PokemonUrl";

export type PokemonSpecies = {
    base_happiness : number,
    capture_rate: number,
    color : PokemonUrl,
    egg_groups: PokemonUrl[],
    evolution_chain: any,
    evolves_from_species: PokemonUrl,
    flavor_text_entries: any[],
    form_descriptions: unknown[],
    forms_switchable: boolean,
    gender_rate: number,
    genera: any[],
    generation: PokemonUrl,
    growth_rate: PokemonUrl,
    habitat: PokemonUrl,
    has_gender_differences: boolean,
    hatch_counter: number,
    id: number,
    is_baby: boolean,
    is_legendary: boolean,
    is_mythical: boolean,
    name: string,
    names: any[],
    order: number,
    pal_park_encounters: any[],
    pokedex_numbers: any[],
    shape: PokemonUrl,
    varieties: any[]
}